# Generated by Django 2.1.2 on 2018-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='avaliable',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='remaining',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
