# Generated by Django 2.1.2 on 2018-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181018_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='occupation',
            field=models.CharField(default='黄绿医生', max_length=50),
            preserve_default=False,
        ),
    ]
